version: "3"
services:
  employeeApi:
    container_name: employeeApiContainer
    build:
      context: .
      dockerfile: ./Dockerfile
    image: employee_api:latest
    ports:
          - "8080:8080"